########################### Options ###########################
[options]
    # colorscheme
    colorscheme_default = "default-reduce"
    colorscheme = "default-reduce"
    colorscheme_bg = "dark"
    enable_guicolors = true
    custom_color_palette = []

    # statusline & tabline
    enable_statusline_tag = true
    enable_statusline_mode = true
    enable_statusline_bfpath = true
    enable_powerline_fonts = true
    enable_tabline_ft_icon = true
    enable_statusline_ft_icon = true
    enable_os_fileformat_icon = true
    buffer_index_type = 4
    windows_index_type = 0
    statusline_unicode_symbols = true
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    statusline_left_sections = ["winnr", "version control info"]
    statusline_right_sections = ["syntax checking", "major mode", "fileformat", "cursorpos", "percentage"]

    # filemanager
    filemanager = "defx"
    enable_vimfiler_filetypeicon = true
    enable_vimfiler_gitstatus = true
    enable_vimfiler_welcome = true
    filetree_direction = "right"
    sidebar_width = 25

    # development
    lint_engine = "ale"
    autocomplete_method = "ycm"
    snippet_engine = "ultisnips"
    lint_on_save = false
    lint_on_the_fly = true
    error_symbol = " "
    warning_symbol = " "
    info_symbol = " "
    autocomplete_parens = true
    enable_language_specific_leader = false
    terminal_runner = true

    hosts_url = "https://raw.githubusercontent.com/racaljk/hosts/master/hosts"

    # projects
    enable_projects_cache = true
    projects_cache_num = 20
    project_rooter_automatically = true
    project_rooter_outermost = false
    project_rooter_patterns = [".git/", "_darcs/", ".hg/", ".bzr/", ".svn/", ".SpaceVim.d/"]

    # misc
    terminal_cursor_shape = 2
    default_indent = 4
    enable_bepo_layout = false
    enable_cursorline = true
    enable_cursorcolumn = false
    enable_key_frequency = false
    relativenumber = true
    escape_key_binding = ""
    expand_tab = true
    max_column = 100

    # SpaceVim
    force_global_config = true
    enable_debug = false
    debug_level = 1
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    default_custom_leader = "<Space>"
    language = "en_US.UTF-8"
    vim_help_language = "en"
    vimcompatible = true
    realtime_leader_guide = true
    search_tools = ["rg", "ag", "ack", "grep", "git"]
    todo_labels = ["@fixme", "@question", "@todo", "@idea"]
    wildignore = "*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg"
    keep_server_alive = true
    auto_disable_touchpad = false

    # plugins
    checkinstall = false
    update_retry_cnt = 2
    plugin_manager_processes = 16
    disabled_plugins = [ 
        "neco-syntax",
        "neoinclude.vim",
        "neosnippet-snippets",
        "neopairs.vim",
        "deoplete-dictionary",
        "CompleteParameter.vim",
        "fcitx.vim",
        "fcitx5.vim",
        "jedi-vim",
        "deoplete-jedi",
    ]

########################### Plugins ###########################
[[custom_plugins]]
    repo = "yangyangxcf/vim-nerd-font-cheatsheets"
    merged = false

[[custom_plugins]]
    repo = "mrbeardad/vim-header"
    merged = false

[[custom_plugins]]
    repo = "mg979/vim-visual-multi"
    merged = false

[[custom_plugins]]
    repo = "Chiel92/vim-autoformat"
    merged = false

########################### Layers ###########################
[[layers]]
    name = "core#banner"

[[layers]]
    name = "core#statusline"

[[layers]]
    name = "core#tabline"

[[layers]]
    name = "core"

[[layers]]
    name = "colorscheme"

[[layers]]
    name = "incsearch"

[[layers]]
    name = "ui"

[[layers]]
    name = "edit"

[[layers]]
    name = "tools"

[[layers]]
    name = "leaderf"

[[layers]]
    name = "git"
    git-plugin = "fugitive"

[[layers]]
  name = "VersionControl"

[[layers]]
    name = "checker"
#
[[layers]]
    name = "autocomplete"
    auto_completion_return_key_behavior = "nil"
    auto_completion_tab_key_behavior = "nil"
    auto_completion_complete_with_key_sequence = "nil"
    auto_completion_enable_snippets_in_popup = true

[[layers]]
    name = "format"
    enable = false

[[layers]]
    name = "chinese"

[[layers]]
    name = "lang#c"

[[layers]]
    name = "lang#markdown"

[[layers]]
    name ="lang#vim"

[[layers]]
    name ="lang#python"

